title: Compétitions et Formations Informatiques de l’universite Laval
title_short: CFI-UL
description: >
  Nous sommes un groupe de passionnés en informatique qui se sont regroupés pour
  participer aux différentes compétitions dans notre domaine. Si vous êtes
  étudiants et que vous avez un intérêt en informatique, venez faire un tour et
  il nous fera plaisir de vous guider pour exploiter votre plein potentiel!
description_suite: >
  Le groupe a été créé en septembre 2017 par des étudiants qui veulent voir leur
  université briller parmi les autres! Connectez-vous sur notre Slack pour être
  à l’affut de tout ce qui se passe à l’intérieur du club! Soit nos formations,
  ateliers, conférences et tout autre événement que nos membres proposent ou
  veulent participer!
# contact:
#   github: https://github.com/CFI-UL

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

markdown: kramdown
exclude:
  - README.md
  - package.json
  - node_modules
  - Gemfile
  - Gemfile.lock

plugins:
  - jekyll-seo-tag
